image: continuumio/miniconda3:latest

tests:
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda env create -f segmed_env.yml
    - source activate segmed
    - pytest